services:
  lt-devin:
    build: .
    tty: true
    stdin_open: true
    profiles:
      - lt-devin
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "pnpm install && cd decks/202602-lt-devin-wiki-mcp && pnpm exec slidev slides.md --remote --port 3030"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lt-devin.rule=Host(`lt-devin.slides.localhost`)"
      - "traefik.http.routers.lt-devin.tls=true"
      - "traefik.http.services.lt-devin.loadbalancer.server.port=3030"

volumes:
  node_modules:
